- name: GIT DEPLOY PLAYBOOK
  hosts: localhost
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
    repository: "FrederickDetrezPXL/2TIN_ResearchProject"
    commitId: "420966cdc84f447892a196d0cc6542247caa8913"

  tasks: 
    - name: Ensure GIT code deploy is started.	
      shell: "aws deploy create-deployment --application-name PE_CLOUD_APP --deployment-group-name PE_CLOUD_DEPLOY_GRP --github-location repository='{{repository}}',commitId='{{commitId}}' --file-exists-behavior OVERWRITE" 
