---
- name: MYSQL PLAYBOOK
  hosts: aws_ec2
  become: true
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"
  tasks: 
    - name: Ensure MySQL is installed.
      yum: 
        name: 
          - mysql
        state: present    
