---
- name: GIT PLAYBOOK
  hosts: aws_ec2
  become: true
  vars: 
    ansible_python_interpreter: "/usr/bin/python2"
  tasks: 
    - name: Ensure GIT is installed.
      yum: 
        name: 
          - git
        state: present    
