---
- name: UNZIP PLAYBOOK
  hosts: aws_ec2
  become: true
  vars: 
    ansible_python_interpreter: "/usr/bin/python2"
  tasks: 
    - name: Ensure UNZIP is installed.
      yum: 
        name: 
          - unzip
        state: present   
